/*
 * kws_nn.cpp - NN glue. The model handling below is lifted from the NN team's
 * esp32_kws_firmware.cpp (kept in reference/) with these RTOS-driven changes only:
 *   - no app_main / tasks / I2S ISR / hop semaphore / event queue: the RTOS project owns them
 *   - no private ring + frontend + feature-matrix access: nn_task receives a SNAPSHOT of the
 *     matrix taken by dsp_task (the live matrix belongs to dsp_task on the other core)
 *   - no internal 1.5 s cooldown: the RTOS owns cooldown (streaming + SIH_COOLDOWN_MS),
 *     nn_task is parked for all of it. The bouncer's hit counter is reset on resume instead.
 *   - failures are logged, not silent
 * Quantization, op list, shape check, dequantization and the leaky bouncer are unchanged.
 */
#include "kws_nn.h"

#include <math.h>
#include <new>
#include <stdint.h>

#include "esp_log.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"

#include "kws_model_data.h" /* g_model[], g_model_len (generated by train_and_quantize.py) */

static const char *TAG = "kws_nn";

#define CONFIDENCE_THRESH  0.85f
#define BOUNCER_TARGET     3

static uint8_t s_arena[KWS_NN_TENSOR_ARENA_BYTES] __attribute__((aligned(16)));
static uint8_t s_resolver_storage[sizeof(tflite::MicroMutableOpResolver<8>)] __attribute__((aligned(8)));
static uint8_t s_interp_storage[sizeof(tflite::MicroInterpreter)] __attribute__((aligned(8)));

static tflite::MicroInterpreter *s_interp;
static TfLiteTensor *s_in;
static TfLiteTensor *s_out;
static float s_in_scale = 1.0f;
static int32_t s_in_zp;
static int s_hits;

/* Q15.16 -> int8 with the model's own input scale / zero point. */
static inline int8_t quantize_input_value(int32_t raw_q)
{
    const float f = (float)raw_q / 65536.0f; /* == q15_16_to_float() */
    int32_t q = (int32_t)lroundf(f / s_in_scale) + s_in_zp;
    if (q > 127) q = 127;
    if (q < -128) q = -128;
    return (int8_t)q;
}

extern "C" {

bool kws_nn_init(void)
{
    auto *resolver = new (s_resolver_storage) tflite::MicroMutableOpResolver<8>();
    resolver->AddDepthwiseConv2D();
    resolver->AddConv2D();
    resolver->AddAdd();
    resolver->AddMean();
    resolver->AddFullyConnected();
    resolver->AddLogistic();
    resolver->AddQuantize();
    resolver->AddDequantize();

    const tflite::Model *model = tflite::GetModel(g_model);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        ESP_LOGE(TAG, "model schema version %u != %d (is g_model really in memory? see notes on the "
                 ".ext_ram.bss section attribute in kws_model_data.h)",
                 (unsigned)model->version(), TFLITE_SCHEMA_VERSION);
        return false;
    }

    s_interp = new (s_interp_storage) tflite::MicroInterpreter(model, *resolver, s_arena, sizeof(s_arena));
    if (s_interp->AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "AllocateTensors failed: tensor arena (%u B) too small", (unsigned)sizeof(s_arena));
        return false;
    }
    s_in = s_interp->input(0);
    s_out = s_interp->output(0);

    if (s_in->type != kTfLiteInt8 || s_in->dims->size < 3 || s_in->dims->data[1] != KWS_FE_CONTEXT_HOPS ||
        s_in->dims->data[2] != KWS_FE_NUM_MEL) {
        ESP_LOGE(TAG, "model input does not match DSP output: expected int8 [1,%d,%d,...]",
                 KWS_FE_CONTEXT_HOPS, KWS_FE_NUM_MEL);
        return false;
    }
    s_in_scale = s_in->params.scale;
    s_in_zp = s_in->params.zero_point;
    s_hits = 0;
    ESP_LOGI(TAG, "model ok: input scale %.6f zp %d, arena used %u of %u B", (double)s_in_scale,
             (int)s_in_zp, (unsigned)s_interp->arena_used_bytes(), (unsigned)sizeof(s_arena));
    return true;
}

void kws_nn_load_input(const kws_fe_matrix_t *matrix)
{
    int8_t *dst = s_in->data.int8;
    for (int t = 0; t < KWS_FE_CONTEXT_HOPS; t++) {
        for (int m = 0; m < KWS_FE_NUM_MEL; m++) {
            dst[t * KWS_FE_NUM_MEL + m] = quantize_input_value((*matrix)[t][m]);
        }
    }
}

bool kws_nn_run(kws_nn_result_t *result)
{
    result->confidence = 0.0f;
    result->triggered = false;
    if (s_interp->Invoke() != kTfLiteOk) {
        return false;
    }
    const float confidence = s_out->params.scale * (float)(s_out->data.int8[0] - s_out->params.zero_point);
    result->confidence = confidence;

    /* Leaky accumulator, not a hard reset (NN team's design). */
    if (confidence > CONFIDENCE_THRESH) {
        s_hits++;
    } else if (s_hits > 0) {
        s_hits--;
    }
    if (s_hits >= BOUNCER_TARGET) {
        s_hits = 0;
        result->triggered = true;
    }
    return true;
}

void kws_nn_reset(void)
{
    s_hits = 0;
}

size_t kws_nn_arena_bytes(void)
{
    return sizeof(s_arena);
}

} /* extern "C" */
